### Pivot Table and Melt

Both pivot_table and melt are functions used in data manipulation with data frames in Python.

pivot_table is used to create a spreadsheet-style pivot table as a DataFrame. It can aggregate and summarize data based on one or more columns, and show the results in a tabular format.

melt is used to transform a wide-format data frame into a long-format data frame. This is useful when you have a data frame with columns that contain different types of data that you want to combine into a single column.

In [1]:
import numpy as np
import pandas as pd

In [2]:
df_books = pd.read_csv('/work/bestsellers.csv', sep=',', header=0)

In [4]:
df_books.head(5)

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction

    "index='Author'" specifies that the pivot table will have authors as the rows.
    "columns='Genre'" specifies that the pivot table will have genres as the columns.
    "values='User Rating'" specifies that the pivot table will contain user ratings as the values.

In [6]:
df_books.pivot_table(index='Author', columns='Genre', values='User Rating')

Genre                       Fiction  Non Fiction
Author
Abraham Verghese                4.6          NaN
Adam Gasiewski                  NaN     4.400000
Adam Mansbach                   4.8          NaN
Adir Levy                       4.8          NaN
Admiral William H. McRaven      NaN     4.700000
...                             ...          ...
Walter Isaacson                 NaN     4.566667
William Davis                   NaN     4.400000
William P. Young                4.6          NaN
Wizards RPG Team                4.8          NaN
Zhi Gang Sha                    NaN     4.600000

[248 rows x 2 columns]

A variation of the pivot table

In [15]:
df_books.pivot_table(index='Year', columns='Genre', values='User Rating', aggfunc='median').round(2)

Genre  Fiction  Non Fiction
Year
2009      4.70         4.60
2010      4.70         4.55
2011      4.70         4.60
2012      4.60         4.60
2013      4.65         4.60
2014      4.70         4.60
2015      4.80         4.70
2016      4.80         4.70
2017      4.80         4.60
2018      4.80         4.70
2019      4.85         4.70

### Melt

In [16]:
df_books[['Name','Genre']].head(5)

                                                Name        Genre
0                      10-Day Green Smoothie Cleanse  Non Fiction
1                                  11/22/63: A Novel      Fiction
2            12 Rules for Life: An Antidote to Chaos  Non Fiction
3                             1984 (Signet Classics)      Fiction
4  5,000 Awesome Facts (About Everything!) (Natio...  Non Fiction

The melt() method unpivots the DataFrame from wide format to long format, effectively stacking the selected columns on top of each other. In this case, it will create a new DataFrame with three columns: 'variable', 'value', and 'index'.

Here's what each column represents:

    'variable': this column contains the original column names that were stacked (i.e., 'Name' and 'Genre').
    'value': this column contains the values from the original columns that were stacked.
    'index': this column contains the row index from the original DataFrame.

In [17]:
df_books[['Name','Genre']].head(5).melt()

  variable                                              value
0     Name                      10-Day Green Smoothie Cleanse
1     Name                                  11/22/63: A Novel
2     Name            12 Rules for Life: An Antidote to Chaos
3     Name                             1984 (Signet Classics)
4     Name  5,000 Awesome Facts (About Everything!) (Natio...
5    Genre                                        Non Fiction
6    Genre                                            Fiction
7    Genre                                        Non Fiction
8    Genre                                            Fiction
9    Genre                                        Non Fiction

The id_vars parameter specifies which column(s) in the original data frame should be used as identifier variables that are kept in the resulting long-format data frame, and the value_vars parameter specifies which column(s) in the original data frame should be "melted" or "stacked" into a single column in the resulting long-format data frame.

In [18]:
df_books.melt(id_vars='Year',value_vars='Genre')

     Year variable        value
0    2016    Genre  Non Fiction
1    2011    Genre      Fiction
2    2018    Genre  Non Fiction
3    2017    Genre      Fiction
4    2019    Genre  Non Fiction
..    ...      ...          ...
545  2019    Genre      Fiction
546  2016    Genre  Non Fiction
547  2017    Genre  Non Fiction
548  2018    Genre  Non Fiction
549  2019    Genre  Non Fiction

[550 rows x 3 columns]

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=8af9fde7-6d07-4638-8fef-c27d1b3023f8' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' > </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>